const data = [
  {
    fullName: "Nickolaus Measures",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Somali",
    ssn: "229-32-7342",
    money: "$794.08",
  },
  {
    fullName: "Stephan Brigdale",
    gender: "Male",
    jobTitle: "Legal Assistant",
    language: "Ndebele",
    ssn: "630-34-3078",
    money: "$931.99",
  },
  {
    fullName: "Khalil Videler",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "Arabic",
    ssn: "660-20-1393",
    money: "$144.44",
  },
  {
    fullName: "Bogey Lampens",
    gender: "Male",
    jobTitle: "Actuary",
    language: "Fijian",
    ssn: "180-87-9044",
    money: "$114.82",
  },
  {
    fullName: "Lilly Abramzon",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Afrikaans",
    ssn: "427-41-9011",
    money: "$741.08",
  },
  {
    fullName: "Chris Phillps",
    gender: "Male",
    jobTitle: "Programmer III",
    language: "German",
    ssn: "148-17-6793",
    money: "$656.60",
  },
  {
    fullName: "Karol Cail",
    gender: "Female",
    jobTitle: "Automation Specialist III",
    language: "Montenegrin",
    ssn: "420-64-8983",
    money: "$860.42",
  },
  {
    fullName: "Ryun Gentile",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "German",
    ssn: "781-12-6141",
    money: "$878.30",
  },
  {
    fullName: "Inessa Bevis",
    gender: "Female",
    jobTitle: "Human Resources Assistant II",
    language: "Hebrew",
    ssn: "278-31-3075",
    money: "$990.73",
  },
  {
    fullName: "Chaim Edlington",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Quechua",
    ssn: "687-88-4688",
    money: "$118.64",
  },
  {
    fullName: "Lissy Altoft",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Thai",
    ssn: "212-52-2611",
    money: "$645.90",
  },
  {
    fullName: "Hube Ludvigsen",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Czech",
    ssn: "425-29-1222",
    money: "$17.24",
  },
  {
    fullName: "Matias Bartoszewicz",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Moldovan",
    ssn: "240-52-4450",
    money: "$650.94",
  },
  {
    fullName: "Miner Antunes",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Thai",
    ssn: "222-77-7197",
    money: "$355.31",
  },
  {
    fullName: "Shermy Danilchenko",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "English",
    ssn: "518-50-0974",
    money: "$705.13",
  },
  {
    fullName: "Aarika Bach",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Yiddish",
    ssn: "528-64-9659",
    money: "$144.41",
  },
  {
    fullName: "Gilemette Pachta",
    gender: "Female",
    jobTitle: "Pharmacist",
    language: "Persian",
    ssn: "279-80-2752",
    money: "$96.89",
  },
  {
    fullName: "Berke Bicksteth",
    gender: "Male",
    jobTitle: "Geologist III",
    language: "Bislama",
    ssn: "637-16-0390",
    money: "$263.39",
  },
  {
    fullName: "Cosette Fallawe",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Northern Sotho",
    ssn: "129-84-6013",
    money: "$967.37",
  },
  {
    fullName: "Norene Bouldon",
    gender: "Female",
    jobTitle: "Automation Specialist IV",
    language: "Marathi",
    ssn: "677-99-7308",
    money: "$255.51",
  },
  {
    fullName: "Louella Otteridge",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Malay",
    ssn: "279-98-7392",
    money: "$685.90",
  },
  {
    fullName: "Verile Poon",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Amharic",
    ssn: "291-28-5582",
    money: "$769.65",
  },
  {
    fullName: "Annadiane Hulbert",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Armenian",
    ssn: "830-02-9698",
    money: "$149.61",
  },
  {
    fullName: "Juliette Stannislawski",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Papiamento",
    ssn: "185-12-3857",
    money: "$893.38",
  },
  {
    fullName: "Waylon Drabble",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Swedish",
    ssn: "820-34-2079",
    money: "$953.80",
  },
  {
    fullName: "Esme Longina",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Punjabi",
    ssn: "533-98-6072",
    money: "$588.06",
  },
  {
    fullName: "Meridith Poinsett",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "Gagauz",
    ssn: "191-12-3698",
    money: "$932.93",
  },
  {
    fullName: "Blake Pfeffer",
    gender: "Male",
    jobTitle: "Professor",
    language: "Guaraní",
    ssn: "188-57-9148",
    money: "$502.02",
  },
  {
    fullName: "Doll Flatt",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Malagasy",
    ssn: "671-61-1242",
    money: "$126.08",
  },
  {
    fullName: "Gleda Dalley",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Tsonga",
    ssn: "351-20-3262",
    money: "$78.48",
  },
  {
    fullName: "Barnett Canty",
    gender: "Male",
    jobTitle: "Legal Assistant",
    language: "Armenian",
    ssn: "815-22-8083",
    money: "$800.30",
  },
  {
    fullName: "Osbert Poleykett",
    gender: "Male",
    jobTitle: "Account Representative I",
    language: "Somali",
    ssn: "550-29-6572",
    money: "$768.99",
  },
  {
    fullName: "Meredith Oxterby",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Dzongkha",
    ssn: "616-66-6293",
    money: "$833.70",
  },
  {
    fullName: "Hetti Titherington",
    gender: "Female",
    jobTitle: "Assistant Media Planner",
    language: "Greek",
    ssn: "890-27-0258",
    money: "$150.90",
  },
  {
    fullName: "Kellia Imeson",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Kyrgyz",
    ssn: "606-97-0001",
    money: "$367.84",
  },
  {
    fullName: "Muffin Callinan",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Lao",
    ssn: "162-91-5111",
    money: "$366.57",
  },
  {
    fullName: "Brent Stanbro",
    gender: "Male",
    jobTitle: "Cost Accountant",
    language: "Tsonga",
    ssn: "256-59-9506",
    money: "$881.99",
  },
  {
    fullName: "Trixie Elcomb",
    gender: "Female",
    jobTitle: "Accountant IV",
    language: "Gujarati",
    ssn: "376-30-3518",
    money: "$121.58",
  },
  {
    fullName: "Silvanus Thomesson",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Icelandic",
    ssn: "812-13-6941",
    money: "$73.76",
  },
  {
    fullName: "Godard Oxtarby",
    gender: "Male",
    jobTitle: "Geologist I",
    language: "Gujarati",
    ssn: "748-66-5313",
    money: "$193.54",
  },
  {
    fullName: "Kiley Finlayson",
    gender: "Male",
    jobTitle: "Research Nurse",
    language: "Hiri Motu",
    ssn: "640-53-2894",
    money: "$766.28",
  },
  {
    fullName: "Bibbie Stallworth",
    gender: "Female",
    jobTitle: "Human Resources Manager",
    language: "Arabic",
    ssn: "845-24-7503",
    money: "$321.33",
  },
  {
    fullName: "Margy McKie",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Amharic",
    ssn: "301-41-4891",
    money: "$361.42",
  },
  {
    fullName: "Cale Brickett",
    gender: "Male",
    jobTitle: "Health Coach I",
    language: "Punjabi",
    ssn: "890-71-0280",
    money: "$462.64",
  },
  {
    fullName: "Gabi Glassman",
    gender: "Female",
    jobTitle: "Senior Sales Associate",
    language: "Danish",
    ssn: "590-13-1508",
    money: "$568.97",
  },
  {
    fullName: "Davita Winterbottom",
    gender: "Female",
    jobTitle: "Senior Cost Accountant",
    language: "Persian",
    ssn: "274-78-7189",
    money: "$259.13",
  },
  {
    fullName: "Dorene Tonkin",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Amharic",
    ssn: "407-68-8570",
    money: "$82.46",
  },
  {
    fullName: "Deloria Goodier",
    gender: "Female",
    jobTitle: "Accounting Assistant III",
    language: "Guaraní",
    ssn: "626-83-9920",
    money: "$248.66",
  },
  {
    fullName: "Gwendolyn Carrier",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "German",
    ssn: "842-86-1810",
    money: "$328.97",
  },
  {
    fullName: "Shurwood Matschuk",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Punjabi",
    ssn: "896-12-7381",
    money: "$81.59",
  },
  {
    fullName: "Tamera Abeau",
    gender: "Female",
    jobTitle: "Senior Developer",
    language: "Tok Pisin",
    ssn: "639-66-4086",
    money: "$566.45",
  },
  {
    fullName: "Riley Mackelworth",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Kazakh",
    ssn: "108-31-0956",
    money: "$423.18",
  },
  {
    fullName: "Kermie Jacobsohn",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Filipino",
    ssn: "779-24-4616",
    money: "$406.47",
  },
  {
    fullName: "Bengt Wynrehame",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Maltese",
    ssn: "377-47-0965",
    money: "$964.90",
  },
  {
    fullName: "Burnaby Kniveton",
    gender: "Male",
    jobTitle: "Director of Sales",
    language: "Northern Sotho",
    ssn: "269-55-5673",
    money: "$520.46",
  },
  {
    fullName: "Hewe Eadmeads",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Czech",
    ssn: "808-05-8796",
    money: "$159.71",
  },
  {
    fullName: "Kaspar Gillimgham",
    gender: "Male",
    jobTitle: "Marketing Manager",
    language: "Hebrew",
    ssn: "545-02-5225",
    money: "$61.89",
  },
  {
    fullName: "Rodina Sibbering",
    gender: "Female",
    jobTitle: "Chemical Engineer",
    language: "Swedish",
    ssn: "646-03-6669",
    money: "$621.62",
  },
  {
    fullName: "Kally Loyley",
    gender: "Female",
    jobTitle: "Health Coach II",
    language: "Moldovan",
    ssn: "866-22-3625",
    money: "$827.00",
  },
  {
    fullName: "Barnabe Goold",
    gender: "Male",
    jobTitle: "Programmer Analyst II",
    language: "German",
    ssn: "446-79-3628",
    money: "$129.04",
  },
  {
    fullName: "Josie Dominiak",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Oriya",
    ssn: "558-67-0544",
    money: "$9.79",
  },
  {
    fullName: "Yvette Cauthra",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Malay",
    ssn: "510-49-1114",
    money: "$695.42",
  },
  {
    fullName: "Mireille Ruddom",
    gender: "Female",
    jobTitle: "Help Desk Operator",
    language: "Polish",
    ssn: "380-22-9343",
    money: "$759.31",
  },
  {
    fullName: "Ignacio Godbolt",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Luxembourgish",
    ssn: "665-76-3675",
    money: "$725.13",
  },
  {
    fullName: "Myrtle Over",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Pashto",
    ssn: "122-26-4490",
    money: "$103.96",
  },
  {
    fullName: "Augie Dossantos",
    gender: "Male",
    jobTitle: "Computer Systems Analyst II",
    language: "Ndebele",
    ssn: "378-37-0934",
    money: "$702.48",
  },
  {
    fullName: "Mitch Hatto",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Belarusian",
    ssn: "599-89-3479",
    money: "$529.52",
  },
  {
    fullName: "Nell Fooks",
    gender: "Female",
    jobTitle: "Administrative Assistant II",
    language: "Kannada",
    ssn: "691-39-6685",
    money: "$157.90",
  },
  {
    fullName: "Kipper Rao",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Aymara",
    ssn: "862-92-1615",
    money: "$153.72",
  },
  {
    fullName: "Donetta Stranks",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Kashmiri",
    ssn: "529-65-1853",
    money: "$815.14",
  },
  {
    fullName: "Rodge Camamile",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Mongolian",
    ssn: "765-93-9862",
    money: "$58.41",
  },
  {
    fullName: "Nonnah Cuffley",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Bulgarian",
    ssn: "786-42-4665",
    money: "$621.50",
  },
  {
    fullName: "Iggie Hunting",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Korean",
    ssn: "638-48-1745",
    money: "$643.57",
  },
  {
    fullName: "Corny Lissandrini",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Papiamento",
    ssn: "561-29-9151",
    money: "$612.79",
  },
  {
    fullName: "Brande Edmans",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Northern Sotho",
    ssn: "430-14-7780",
    money: "$210.54",
  },
  {
    fullName: "Doreen Papachristophorou",
    gender: "Female",
    jobTitle: "Account Representative IV",
    language: "French",
    ssn: "259-55-0485",
    money: "$542.70",
  },
  {
    fullName: "Jerrine Criag",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Kyrgyz",
    ssn: "105-36-9957",
    money: "$2.30",
  },
  {
    fullName: "Devland Steventon",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "Haitian Creole",
    ssn: "615-79-4224",
    money: "$180.13",
  },
  {
    fullName: "Dietrich Shrimpton",
    gender: "Male",
    jobTitle: "Administrative Assistant II",
    language: "Chinese",
    ssn: "187-09-2986",
    money: "$973.58",
  },
  {
    fullName: "Minnie Golledge",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Hindi",
    ssn: "814-31-6444",
    money: "$7.72",
  },
  {
    fullName: "Federico Aiskovitch",
    gender: "Male",
    jobTitle: "General Manager",
    language: "Belarusian",
    ssn: "125-13-7192",
    money: "$431.54",
  },
  {
    fullName: "Brion Kenealy",
    gender: "Male",
    jobTitle: "Web Developer III",
    language: "Swati",
    ssn: "321-77-6741",
    money: "$327.34",
  },
  {
    fullName: "Cindee Worsnip",
    gender: "Female",
    jobTitle: "Software Engineer III",
    language: "Mongolian",
    ssn: "203-91-1998",
    money: "$726.28",
  },
  {
    fullName: "Annabell Purtell",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Estonian",
    ssn: "694-20-5427",
    money: "$608.07",
  },
  {
    fullName: "Chilton Roddy",
    gender: "Male",
    jobTitle: "Computer Systems Analyst II",
    language: "Armenian",
    ssn: "301-70-0873",
    money: "$867.98",
  },
  {
    fullName: "Moses McCutcheon",
    gender: "Male",
    jobTitle: "Systems Administrator II",
    language: "Chinese",
    ssn: "882-87-1758",
    money: "$483.25",
  },
  {
    fullName: "Eleni Berggren",
    gender: "Female",
    jobTitle: "Chemical Engineer",
    language: "Dhivehi",
    ssn: "279-63-1804",
    money: "$170.57",
  },
  {
    fullName: "Giuseppe Mullard",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Dutch",
    ssn: "171-34-4150",
    money: "$176.48",
  },
  {
    fullName: "Morey Heritege",
    gender: "Male",
    jobTitle: "Legal Assistant",
    language: "Kyrgyz",
    ssn: "733-59-4251",
    money: "$814.41",
  },
  {
    fullName: "Xena Jouanet",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Finnish",
    ssn: "215-75-8265",
    money: "$840.47",
  },
  {
    fullName: "Benn Cabrales",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Afrikaans",
    ssn: "301-05-7842",
    money: "$959.06",
  },
  {
    fullName: "Ira Kemetz",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Guaraní",
    ssn: "696-82-0477",
    money: "$829.71",
  },
  {
    fullName: "Johan Burton",
    gender: "Male",
    jobTitle: "Graphic Designer",
    language: "Catalan",
    ssn: "282-38-4900",
    money: "$44.89",
  },
  {
    fullName: "Akim Hemshall",
    gender: "Male",
    jobTitle: "Database Administrator I",
    language: "Danish",
    ssn: "177-52-8108",
    money: "$204.19",
  },
  {
    fullName: "Lothaire Scorey",
    gender: "Male",
    jobTitle: "Compensation Analyst",
    language: "Albanian",
    ssn: "226-67-2182",
    money: "$194.80",
  },
  {
    fullName: "Burtie Windress",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Nepali",
    ssn: "612-42-7347",
    money: "$137.14",
  },
  {
    fullName: "Florence Cahn",
    gender: "Female",
    jobTitle: "VP Marketing",
    language: "Estonian",
    ssn: "353-39-9631",
    money: "$972.37",
  },
  {
    fullName: "Lori Bracey",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "Tajik",
    ssn: "403-44-0849",
    money: "$167.59",
  },
  {
    fullName: "Loren Lunk",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Georgian",
    ssn: "713-14-3125",
    money: "$407.30",
  },
  {
    fullName: "Levin Painter",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Malagasy",
    ssn: "308-54-8587",
    money: "$412.55",
  },
  {
    fullName: "Lorrie Linnemann",
    gender: "Female",
    jobTitle: "Administrative Officer",
    language: "Thai",
    ssn: "559-71-4219",
    money: "$156.62",
  },
  {
    fullName: "Julieta Titley",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Catalan",
    ssn: "583-12-5978",
    money: "$541.40",
  },
  {
    fullName: "Kathie Gregoratti",
    gender: "Female",
    jobTitle: "Professor",
    language: "Hiri Motu",
    ssn: "251-22-1147",
    money: "$584.23",
  },
  {
    fullName: "Meier Apted",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "Azeri",
    ssn: "497-67-2690",
    money: "$721.93",
  },
  {
    fullName: "Jodie Sudran",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Bosnian",
    ssn: "667-40-7754",
    money: "$720.11",
  },
  {
    fullName: "Clementine Baldree",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Khmer",
    ssn: "459-81-1545",
    money: "$298.08",
  },
  {
    fullName: "Sondra Goodhew",
    gender: "Female",
    jobTitle: "Administrative Assistant IV",
    language: "Tetum",
    ssn: "169-19-5561",
    money: "$876.12",
  },
  {
    fullName: "Quincy Tassaker",
    gender: "Male",
    jobTitle: "Web Designer IV",
    language: "Macedonian",
    ssn: "447-30-9161",
    money: "$545.12",
  },
  {
    fullName: "Ramsey Kensy",
    gender: "Male",
    jobTitle: "Programmer II",
    language: "Amharic",
    ssn: "869-74-4310",
    money: "$31.86",
  },
  {
    fullName: "Gerek Howlett",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "German",
    ssn: "452-31-5152",
    money: "$317.43",
  },
  {
    fullName: "Anne-marie Ragsdale",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Kazakh",
    ssn: "805-92-9817",
    money: "$686.20",
  },
  {
    fullName: "Alvan Dopson",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "English",
    ssn: "790-31-3262",
    money: "$866.99",
  },
  {
    fullName: "Darlene Stratton",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "Macedonian",
    ssn: "165-43-9092",
    money: "$110.58",
  },
  {
    fullName: "Uriel Brown",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Georgian",
    ssn: "819-85-3588",
    money: "$930.60",
  },
  {
    fullName: "Reg Lowdyane",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Swedish",
    ssn: "529-19-0147",
    money: "$322.22",
  },
  {
    fullName: "Dorelia Jimes",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Moldovan",
    ssn: "769-25-8796",
    money: "$228.01",
  },
  {
    fullName: "Ned Aulds",
    gender: "Male",
    jobTitle: "Senior Quality Engineer",
    language: "Northern Sotho",
    ssn: "340-90-5872",
    money: "$144.11",
  },
  {
    fullName: "Bibbye Rowthorn",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "West Frisian",
    ssn: "486-52-9471",
    money: "$494.11",
  },
  {
    fullName: "Jonell Mackrill",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Japanese",
    ssn: "855-37-4457",
    money: "$459.70",
  },
  {
    fullName: "Stanwood Mallam",
    gender: "Male",
    jobTitle: "Database Administrator I",
    language: "Filipino",
    ssn: "161-59-7425",
    money: "$933.53",
  },
  {
    fullName: "Barney Di Nisco",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Ndebele",
    ssn: "859-31-2708",
    money: "$593.08",
  },
  {
    fullName: "Xenos Sympson",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Polish",
    ssn: "389-95-7721",
    money: "$65.62",
  },
  {
    fullName: "Hyatt MacTrustram",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "New Zealand Sign Language",
    ssn: "444-88-8697",
    money: "$62.13",
  },
  {
    fullName: "Mick Shipley",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "Punjabi",
    ssn: "201-96-8979",
    money: "$525.93",
  },
  {
    fullName: "Melody Swayton",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Māori",
    ssn: "323-84-3290",
    money: "$15.35",
  },
  {
    fullName: "Lucias Chill",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Aymara",
    ssn: "561-59-3505",
    money: "$401.57",
  },
  {
    fullName: "Constantine Thinn",
    gender: "Male",
    jobTitle: "Web Designer II",
    language: "Assamese",
    ssn: "179-16-1554",
    money: "$526.42",
  },
  {
    fullName: "Sherry Devo",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Icelandic",
    ssn: "549-08-4788",
    money: "$696.74",
  },
  {
    fullName: "Papageno Bartolomucci",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Swedish",
    ssn: "207-16-8910",
    money: "$831.77",
  },
  {
    fullName: "Creigh Barwis",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Guaraní",
    ssn: "383-10-9378",
    money: "$886.04",
  },
  {
    fullName: "Burtie Ciccottini",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Yiddish",
    ssn: "601-83-2003",
    money: "$734.18",
  },
  {
    fullName: "Melesa Brumble",
    gender: "Female",
    jobTitle: "Database Administrator III",
    language: "Malayalam",
    ssn: "874-30-1221",
    money: "$395.36",
  },
  {
    fullName: "Bradney McCaughey",
    gender: "Male",
    jobTitle: "Accountant IV",
    language: "Nepali",
    ssn: "855-46-8963",
    money: "$51.38",
  },
  {
    fullName: "Fanechka Mathy",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Somali",
    ssn: "410-79-9246",
    money: "$612.78",
  },
  {
    fullName: "Sofie Giraudeau",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Arabic",
    ssn: "487-08-8454",
    money: "$924.20",
  },
  {
    fullName: "Doll Kiff",
    gender: "Female",
    jobTitle: "Help Desk Operator",
    language: "Kashmiri",
    ssn: "763-18-5706",
    money: "$70.16",
  },
  {
    fullName: "Templeton Chowne",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Persian",
    ssn: "704-19-5104",
    money: "$197.08",
  },
  {
    fullName: "Chrissie Bode",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Tamil",
    ssn: "823-16-1645",
    money: "$90.09",
  },
  {
    fullName: "Ulrikaumeko Gwynne",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Korean",
    ssn: "223-62-5329",
    money: "$369.96",
  },
  {
    fullName: "Haywood Artin",
    gender: "Male",
    jobTitle: "Biostatistician III",
    language: "Punjabi",
    ssn: "102-55-8046",
    money: "$436.77",
  },
  {
    fullName: "Clerissa Brownhall",
    gender: "Female",
    jobTitle: "Accountant I",
    language: "German",
    ssn: "407-88-3764",
    money: "$775.03",
  },
  {
    fullName: "Tiphanie Varsey",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Croatian",
    ssn: "576-05-9858",
    money: "$287.83",
  },
  {
    fullName: "Temple Denty",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "New Zealand Sign Language",
    ssn: "274-44-3626",
    money: "$156.75",
  },
  {
    fullName: "Elfrieda Larkby",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Latvian",
    ssn: "502-44-5669",
    money: "$14.61",
  },
  {
    fullName: "Foster Chsteney",
    gender: "Male",
    jobTitle: "Electrical Engineer",
    language: "Kannada",
    ssn: "143-69-5042",
    money: "$948.28",
  },
  {
    fullName: "Goldy Orbon",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Swedish",
    ssn: "770-32-6698",
    money: "$476.63",
  },
  {
    fullName: "Sande Indruch",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Polish",
    ssn: "477-61-8120",
    money: "$496.04",
  },
  {
    fullName: "Malina Fitzroy",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Greek",
    ssn: "433-90-7752",
    money: "$528.29",
  },
  {
    fullName: "Seana Pringour",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Nepali",
    ssn: "557-78-9585",
    money: "$483.20",
  },
  {
    fullName: "Fairfax Bellhanger",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Croatian",
    ssn: "244-99-3615",
    money: "$927.08",
  },
  {
    fullName: "Debra Coal",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "German",
    ssn: "488-04-4158",
    money: "$771.73",
  },
  {
    fullName: "Anderea Duigan",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Swahili",
    ssn: "423-71-4909",
    money: "$915.65",
  },
  {
    fullName: "Ciel Decaze",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Malay",
    ssn: "715-84-3851",
    money: "$57.30",
  },
  {
    fullName: "Lida Betke",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Dhivehi",
    ssn: "818-94-5366",
    money: "$68.98",
  },
  {
    fullName: "Thane Strand",
    gender: "Male",
    jobTitle: "Safety Technician II",
    language: "Czech",
    ssn: "528-17-9820",
    money: "$951.04",
  },
  {
    fullName: "Zoe Stace",
    gender: "Female",
    jobTitle: "Chemical Engineer",
    language: "Kashmiri",
    ssn: "674-62-0171",
    money: "$700.53",
  },
  {
    fullName: "Arte Casale",
    gender: "Male",
    jobTitle: "Media Manager II",
    language: "Hindi",
    ssn: "700-96-8799",
    money: "$341.06",
  },
  {
    fullName: "Jackie Tupper",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Papiamento",
    ssn: "331-63-6541",
    money: "$877.25",
  },
  {
    fullName: "Harri Mucci",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Korean",
    ssn: "130-58-0698",
    money: "$669.61",
  },
  {
    fullName: "Charita Ravenscraft",
    gender: "Female",
    jobTitle: "Senior Sales Associate",
    language: "Luxembourgish",
    ssn: "581-82-3915",
    money: "$876.42",
  },
  {
    fullName: "Irma Keats",
    gender: "Female",
    jobTitle: "Geologist I",
    language: "Sotho",
    ssn: "249-10-6165",
    money: "$832.99",
  },
  {
    fullName: "Blondelle Nangle",
    gender: "Female",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Hiri Motu",
    ssn: "440-29-8568",
    money: "$760.95",
  },
  {
    fullName: "Lacie Issacoff",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Romanian",
    ssn: "640-58-3571",
    money: "$820.80",
  },
  {
    fullName: "Willis Jakubovsky",
    gender: "Male",
    jobTitle: "Marketing Assistant",
    language: "Tswana",
    ssn: "290-58-9316",
    money: "$397.13",
  },
  {
    fullName: "Sheppard Krolik",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "West Frisian",
    ssn: "613-23-4333",
    money: "$334.13",
  },
  {
    fullName: "Elna Wimes",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Chinese",
    ssn: "468-41-0915",
    money: "$508.63",
  },
  {
    fullName: "Emilio Heibel",
    gender: "Male",
    jobTitle: "Human Resources Manager",
    language: "Bislama",
    ssn: "110-71-4124",
    money: "$887.58",
  },
  {
    fullName: "Munmro Prium",
    gender: "Male",
    jobTitle: "Operator",
    language: "Arabic",
    ssn: "138-01-5684",
    money: "$810.03",
  },
  {
    fullName: "Billy McMearty",
    gender: "Female",
    jobTitle: "Office Assistant IV",
    language: "Norwegian",
    ssn: "136-50-6292",
    money: "$69.46",
  },
  {
    fullName: "Lizzy Southers",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Bislama",
    ssn: "634-29-8587",
    money: "$333.20",
  },
  {
    fullName: "Harper Thelwll",
    gender: "Male",
    jobTitle: "Recruiter",
    language: "Punjabi",
    ssn: "881-13-7947",
    money: "$285.21",
  },
  {
    fullName: "Geoffrey Rubke",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Tamil",
    ssn: "827-54-8975",
    money: "$449.79",
  },
  {
    fullName: "Garnette Vedstra",
    gender: "Female",
    jobTitle: "Research Assistant I",
    language: "Indonesian",
    ssn: "189-27-0695",
    money: "$470.66",
  },
  {
    fullName: "Shari Gammons",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Maltese",
    ssn: "184-42-2240",
    money: "$627.05",
  },
  {
    fullName: "Kerr Rennix",
    gender: "Male",
    jobTitle: "Accounting Assistant I",
    language: "Māori",
    ssn: "267-96-0087",
    money: "$409.46",
  },
  {
    fullName: "Karilynn Greenstreet",
    gender: "Female",
    jobTitle: "Safety Technician II",
    language: "Bislama",
    ssn: "226-75-7906",
    money: "$99.70",
  },
  {
    fullName: "Dew Walliker",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "Portuguese",
    ssn: "626-36-8957",
    money: "$731.47",
  },
  {
    fullName: "Jackie Tinn",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Filipino",
    ssn: "574-81-4485",
    money: "$981.78",
  },
  {
    fullName: "Monique Grote",
    gender: "Female",
    jobTitle: "Biostatistician IV",
    language: "Amharic",
    ssn: "702-92-7143",
    money: "$724.01",
  },
  {
    fullName: "Mac Lean",
    gender: "Male",
    jobTitle: "Financial Advisor",
    language: "Maltese",
    ssn: "831-74-5502",
    money: "$152.64",
  },
  {
    fullName: "Fabio Broadwood",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Italian",
    ssn: "463-90-2838",
    money: "$2.96",
  },
  {
    fullName: "Nolana Masedon",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Filipino",
    ssn: "695-17-8241",
    money: "$808.30",
  },
  {
    fullName: "Rooney Rudd",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Ndebele",
    ssn: "829-45-8446",
    money: "$890.96",
  },
  {
    fullName: "Mario Cotmore",
    gender: "Male",
    jobTitle: "Database Administrator I",
    language: "Korean",
    ssn: "203-15-9327",
    money: "$258.36",
  },
  {
    fullName: "Lesley Middas",
    gender: "Female",
    jobTitle: "Media Manager I",
    language: "Gagauz",
    ssn: "466-95-4304",
    money: "$573.87",
  },
  {
    fullName: "Richie Byrkmyr",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "Papiamento",
    ssn: "701-95-6497",
    money: "$676.56",
  },
  {
    fullName: "Ettore Gaskin",
    gender: "Male",
    jobTitle: "Web Designer I",
    language: "Fijian",
    ssn: "379-86-6920",
    money: "$707.52",
  },
  {
    fullName: "Ford Eskriet",
    gender: "Male",
    jobTitle: "Safety Technician IV",
    language: "Malagasy",
    ssn: "283-54-8153",
    money: "$694.70",
  },
  {
    fullName: "Morse Goard",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Malay",
    ssn: "749-80-4533",
    money: "$686.94",
  },
  {
    fullName: "Kelila Day",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Bulgarian",
    ssn: "551-18-6634",
    money: "$659.13",
  },
  {
    fullName: "Randi Corten",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Chinese",
    ssn: "663-45-9852",
    money: "$672.29",
  },
  {
    fullName: "Beryle Rodenburg",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Croatian",
    ssn: "573-09-6252",
    money: "$211.75",
  },
  {
    fullName: "Vanessa Steenson",
    gender: "Female",
    jobTitle: "Software Engineer IV",
    language: "English",
    ssn: "408-39-4014",
    money: "$142.04",
  },
  {
    fullName: "Desdemona Mackro",
    gender: "Female",
    jobTitle: "Professor",
    language: "Moldovan",
    ssn: "751-35-5581",
    money: "$674.38",
  },
  {
    fullName: "Selby Wedmore.",
    gender: "Male",
    jobTitle: "Programmer Analyst IV",
    language: "Somali",
    ssn: "684-89-7870",
    money: "$52.37",
  },
  {
    fullName: "Marcie Scriver",
    gender: "Female",
    jobTitle: "Human Resources Manager",
    language: "Danish",
    ssn: "672-88-1729",
    money: "$999.48",
  },
  {
    fullName: "Shay Hunnicutt",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Montenegrin",
    ssn: "665-54-9931",
    money: "$340.30",
  },
  {
    fullName: "Clevie Conachy",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "Aymara",
    ssn: "503-52-7357",
    money: "$650.50",
  },
  {
    fullName: "Jaimie Cocks",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Haitian Creole",
    ssn: "754-74-2139",
    money: "$454.98",
  },
  {
    fullName: "Sybilla Van Weedenburg",
    gender: "Female",
    jobTitle: "Web Designer III",
    language: "Chinese",
    ssn: "860-39-6358",
    money: "$567.53",
  },
  {
    fullName: "Egbert Lynskey",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Thai",
    ssn: "547-06-5284",
    money: "$608.29",
  },
  {
    fullName: "Wang Blandford",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Punjabi",
    ssn: "662-31-7081",
    money: "$775.51",
  },
  {
    fullName: "Mel Shepley",
    gender: "Male",
    jobTitle: "Staff Accountant I",
    language: "Burmese",
    ssn: "112-85-0691",
    money: "$21.50",
  },
  {
    fullName: "Cris Heindrich",
    gender: "Male",
    jobTitle: "Web Designer III",
    language: "Yiddish",
    ssn: "548-11-2310",
    money: "$384.93",
  },
  {
    fullName: "Olivia Filyukov",
    gender: "Female",
    jobTitle: "Research Assistant IV",
    language: "Danish",
    ssn: "782-31-3208",
    money: "$709.38",
  },
  {
    fullName: "Olva Diviney",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Spanish",
    ssn: "447-88-5933",
    money: "$591.14",
  },
  {
    fullName: "Micah Poundsford",
    gender: "Male",
    jobTitle: "Programmer Analyst II",
    language: "Italian",
    ssn: "748-28-7048",
    money: "$832.97",
  },
  {
    fullName: "Caryl Kleehuhler",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Gujarati",
    ssn: "893-15-0021",
    money: "$653.59",
  },
  {
    fullName: "Adelina Colson",
    gender: "Female",
    jobTitle: "Software Engineer IV",
    language: "Czech",
    ssn: "467-32-1050",
    money: "$15.68",
  },
  {
    fullName: "Gabriela Hambrook",
    gender: "Female",
    jobTitle: "Systems Administrator II",
    language: "Moldovan",
    ssn: "291-76-9283",
    money: "$350.52",
  },
  {
    fullName: "Matty Cutmere",
    gender: "Female",
    jobTitle: "Account Representative IV",
    language: "Burmese",
    ssn: "336-88-2620",
    money: "$918.77",
  },
  {
    fullName: "Annis Seamans",
    gender: "Female",
    jobTitle: "Systems Administrator I",
    language: "Swati",
    ssn: "249-56-8879",
    money: "$584.75",
  },
  {
    fullName: "Krissy Matschke",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Estonian",
    ssn: "821-48-9208",
    money: "$562.53",
  },
  {
    fullName: "Shellysheldon Reveland",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Kyrgyz",
    ssn: "267-20-8958",
    money: "$132.10",
  },
  {
    fullName: "Carmina Crumbie",
    gender: "Female",
    jobTitle: "Professor",
    language: "Kashmiri",
    ssn: "808-91-2212",
    money: "$859.13",
  },
  {
    fullName: "Tilda Sexti",
    gender: "Female",
    jobTitle: "Design Engineer",
    language: "Icelandic",
    ssn: "761-61-4964",
    money: "$340.05",
  },
  {
    fullName: "Birch Cesco",
    gender: "Male",
    jobTitle: "Electrical Engineer",
    language: "Bulgarian",
    ssn: "160-50-5145",
    money: "$978.35",
  },
  {
    fullName: "Fabiano Schonfelder",
    gender: "Male",
    jobTitle: "Geologist II",
    language: "Zulu",
    ssn: "208-85-8223",
    money: "$491.81",
  },
  {
    fullName: "Pollyanna Scoggin",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Dhivehi",
    ssn: "285-90-8799",
    money: "$597.03",
  },
  {
    fullName: "Sylvia Nickoll",
    gender: "Female",
    jobTitle: "Web Designer I",
    language: "Filipino",
    ssn: "281-86-1227",
    money: "$729.70",
  },
  {
    fullName: "Hattie Avey",
    gender: "Female",
    jobTitle: "Geologist II",
    language: "Quechua",
    ssn: "248-75-7405",
    money: "$823.46",
  },
  {
    fullName: "Amargo Farnill",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Malagasy",
    ssn: "555-22-7418",
    money: "$588.67",
  },
  {
    fullName: "Elonore Westwick",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Hiri Motu",
    ssn: "718-99-2008",
    money: "$612.91",
  },
  {
    fullName: "Susan Crowdace",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Irish Gaelic",
    ssn: "421-09-0932",
    money: "$353.36",
  },
  {
    fullName: "Giffy Noton",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Montenegrin",
    ssn: "313-40-0873",
    money: "$618.29",
  },
  {
    fullName: "Hermia Fonso",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Kashmiri",
    ssn: "115-22-9317",
    money: "$292.28",
  },
  {
    fullName: "Engelbert Menichillo",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Tok Pisin",
    ssn: "515-83-5707",
    money: "$196.62",
  },
  {
    fullName: "Steven Gannaway",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Amharic",
    ssn: "177-81-9742",
    money: "$303.58",
  },
  {
    fullName: "Emerson Rickert",
    gender: "Male",
    jobTitle: "Information Systems Manager",
    language: "English",
    ssn: "538-54-2819",
    money: "$304.90",
  },
  {
    fullName: "Jermaine Backshill",
    gender: "Female",
    jobTitle: "Physical Therapy Assistant",
    language: "Finnish",
    ssn: "681-06-8277",
    money: "$47.28",
  },
  {
    fullName: "Angeli Melrose",
    gender: "Male",
    jobTitle: "Nuclear Power Engineer",
    language: "Hindi",
    ssn: "496-37-0912",
    money: "$603.72",
  },
  {
    fullName: "Horst Eyers",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Armenian",
    ssn: "711-18-7113",
    money: "$475.68",
  },
  {
    fullName: "Wilona Sabin",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Portuguese",
    ssn: "744-10-1968",
    money: "$442.07",
  },
  {
    fullName: "Cyrus Cornelius",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "West Frisian",
    ssn: "660-28-5522",
    money: "$832.27",
  },
  {
    fullName: "Margarette Dargavel",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Kazakh",
    ssn: "817-50-8755",
    money: "$730.69",
  },
  {
    fullName: "Alayne Sclanders",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Bulgarian",
    ssn: "428-37-7920",
    money: "$788.00",
  },
  {
    fullName: "Lalo Tynemouth",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Telugu",
    ssn: "817-08-7577",
    money: "$379.12",
  },
  {
    fullName: "Chad Leaf",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Swati",
    ssn: "274-88-8867",
    money: "$276.82",
  },
  {
    fullName: "Noe Baugh",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Hebrew",
    ssn: "756-53-5242",
    money: "$941.56",
  },
  {
    fullName: "Demetra Case",
    gender: "Female",
    jobTitle: "Senior Developer",
    language: "Luxembourgish",
    ssn: "107-98-3142",
    money: "$661.85",
  },
  {
    fullName: "Shani Dine-Hart",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "German",
    ssn: "838-82-4896",
    money: "$209.96",
  },
  {
    fullName: "Lorens Papierz",
    gender: "Male",
    jobTitle: "VP Sales",
    language: "Maltese",
    ssn: "755-96-4471",
    money: "$119.86",
  },
  {
    fullName: "Creighton Draycott",
    gender: "Male",
    jobTitle: "Programmer Analyst IV",
    language: "Arabic",
    ssn: "149-98-9356",
    money: "$899.10",
  },
  {
    fullName: "Reggi Sherlock",
    gender: "Female",
    jobTitle: "Office Assistant I",
    language: "Malay",
    ssn: "557-12-1496",
    money: "$211.31",
  },
  {
    fullName: "Claudia Bittany",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Irish Gaelic",
    ssn: "524-43-1712",
    money: "$985.03",
  },
  {
    fullName: "Phip Lanham",
    gender: "Male",
    jobTitle: "Biostatistician II",
    language: "Luxembourgish",
    ssn: "598-08-4274",
    money: "$671.72",
  },
  {
    fullName: "Torrence Robertz",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Bengali",
    ssn: "885-18-4565",
    money: "$148.58",
  },
  {
    fullName: "Dulci Dunphie",
    gender: "Female",
    jobTitle: "Professor",
    language: "Irish Gaelic",
    ssn: "895-95-9829",
    money: "$384.90",
  },
  {
    fullName: "Lem Kyberd",
    gender: "Male",
    jobTitle: "Programmer I",
    language: "Khmer",
    ssn: "461-10-1763",
    money: "$575.71",
  },
  {
    fullName: "Leandra Glassard",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Georgian",
    ssn: "372-86-1093",
    money: "$960.31",
  },
  {
    fullName: "Ronda McGlaughn",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "Finnish",
    ssn: "698-61-9184",
    money: "$562.50",
  },
  {
    fullName: "Hurlee Mulloch",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Portuguese",
    ssn: "891-32-6752",
    money: "$681.82",
  },
  {
    fullName: "Vidovik Bulfit",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Latvian",
    ssn: "513-50-0221",
    money: "$649.87",
  },
  {
    fullName: "Lexine Olliar",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Tetum",
    ssn: "653-31-6614",
    money: "$620.70",
  },
  {
    fullName: "Quint Pendrill",
    gender: "Male",
    jobTitle: "Electrical Engineer",
    language: "Somali",
    ssn: "709-73-7152",
    money: "$785.40",
  },
  {
    fullName: "Moss McGrotty",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Swati",
    ssn: "651-10-4302",
    money: "$521.02",
  },
  {
    fullName: "Mada McNee",
    gender: "Female",
    jobTitle: "Civil Engineer",
    language: "Korean",
    ssn: "116-07-5568",
    money: "$815.30",
  },
  {
    fullName: "Fritz Kearton",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Māori",
    ssn: "131-92-8136",
    money: "$293.28",
  },
  {
    fullName: "Vyky Goulbourne",
    gender: "Female",
    jobTitle: "Software Engineer III",
    language: "Lithuanian",
    ssn: "317-63-0842",
    money: "$312.15",
  },
  {
    fullName: "Andrea Keigher",
    gender: "Male",
    jobTitle: "Nurse",
    language: "Dhivehi",
    ssn: "722-80-0823",
    money: "$117.39",
  },
  {
    fullName: "Tymon Szymanski",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Malay",
    ssn: "451-80-5909",
    money: "$306.81",
  },
  {
    fullName: "Prent Harmes",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "Finnish",
    ssn: "412-50-4259",
    money: "$244.86",
  },
  {
    fullName: "Pren Cesconi",
    gender: "Male",
    jobTitle: "Software Engineer IV",
    language: "Bengali",
    ssn: "272-38-4077",
    money: "$464.03",
  },
  {
    fullName: "Cyrillus McGeoch",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Moldovan",
    ssn: "480-55-1359",
    money: "$602.15",
  },
  {
    fullName: "Hayward Mollison",
    gender: "Male",
    jobTitle: "VP Sales",
    language: "Catalan",
    ssn: "414-34-9946",
    money: "$847.04",
  },
  {
    fullName: "Edith Cromack",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Icelandic",
    ssn: "231-05-3109",
    money: "$506.13",
  },
  {
    fullName: "Kerwin Fooks",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Tok Pisin",
    ssn: "131-84-5816",
    money: "$156.13",
  },
  {
    fullName: "Berta Jiracek",
    gender: "Female",
    jobTitle: "Professor",
    language: "Irish Gaelic",
    ssn: "344-09-3505",
    money: "$200.29",
  },
  {
    fullName: "Zeb Shaw",
    gender: "Male",
    jobTitle: "Software Test Engineer I",
    language: "Azeri",
    ssn: "859-04-2262",
    money: "$15.41",
  },
  {
    fullName: "Evelyn Toffanelli",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Nepali",
    ssn: "672-31-3316",
    money: "$831.86",
  },
  {
    fullName: "Selene Doody",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Assamese",
    ssn: "364-44-9946",
    money: "$521.48",
  },
  {
    fullName: "Wallis Bosden",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Catalan",
    ssn: "372-11-8402",
    money: "$254.93",
  },
  {
    fullName: "Lee Gosselin",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Nepali",
    ssn: "761-78-4820",
    money: "$430.80",
  },
  {
    fullName: "Valentin Kabisch",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Punjabi",
    ssn: "683-04-4206",
    money: "$891.66",
  },
  {
    fullName: "Thaddus Hazael",
    gender: "Male",
    jobTitle: "Assistant Media Planner",
    language: "Quechua",
    ssn: "363-16-0825",
    money: "$514.04",
  },
  {
    fullName: "Giffer Simoni",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Dzongkha",
    ssn: "893-34-4336",
    money: "$773.81",
  },
  {
    fullName: "Cari Perview",
    gender: "Female",
    jobTitle: "Civil Engineer",
    language: "Marathi",
    ssn: "597-99-2609",
    money: "$694.37",
  },
  {
    fullName: "Shamus Rosenzwig",
    gender: "Male",
    jobTitle: "Geologist III",
    language: "Burmese",
    ssn: "104-74-8742",
    money: "$656.19",
  },
  {
    fullName: "Dionisio Patron",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Gagauz",
    ssn: "581-17-2699",
    money: "$459.76",
  },
  {
    fullName: "Lynnett Baseley",
    gender: "Female",
    jobTitle: "Sales Representative",
    language: "Albanian",
    ssn: "791-40-6088",
    money: "$507.58",
  },
  {
    fullName: "Margie Dreinan",
    gender: "Female",
    jobTitle: "Computer Systems Analyst IV",
    language: "Croatian",
    ssn: "420-80-1949",
    money: "$621.15",
  },
  {
    fullName: "Shena Zambon",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Montenegrin",
    ssn: "767-52-0771",
    money: "$912.82",
  },
  {
    fullName: "Parke Ferschke",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Swati",
    ssn: "851-90-7145",
    money: "$65.06",
  },
  {
    fullName: "Avery Janosevic",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Norwegian",
    ssn: "552-43-9592",
    money: "$989.25",
  },
  {
    fullName: "Horatius Ghidelli",
    gender: "Male",
    jobTitle: "Director of Sales",
    language: "Polish",
    ssn: "465-92-2154",
    money: "$515.82",
  },
  {
    fullName: "Eloisa Bees",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Amharic",
    ssn: "627-20-0465",
    money: "$134.84",
  },
  {
    fullName: "Bevon Dalziel",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Korean",
    ssn: "591-22-6392",
    money: "$581.95",
  },
  {
    fullName: "Risa Pemble",
    gender: "Female",
    jobTitle: "Automation Specialist IV",
    language: "Kurdish",
    ssn: "793-19-9974",
    money: "$181.79",
  },
  {
    fullName: "Nate Ebourne",
    gender: "Male",
    jobTitle: "VP Accounting",
    language: "Tswana",
    ssn: "881-64-5009",
    money: "$281.48",
  },
  {
    fullName: "Lorinda Limpertz",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Croatian",
    ssn: "689-43-8280",
    money: "$107.98",
  },
  {
    fullName: "Pandora De Courtney",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Luxembourgish",
    ssn: "491-54-3108",
    money: "$862.38",
  },
  {
    fullName: "Eddie Lowcock",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Arabic",
    ssn: "784-93-7016",
    money: "$890.95",
  },
  {
    fullName: "Hadley Maisey",
    gender: "Male",
    jobTitle: "Research Nurse",
    language: "Malayalam",
    ssn: "636-43-1492",
    money: "$531.65",
  },
  {
    fullName: "Tobye Aubin",
    gender: "Female",
    jobTitle: "Geologist I",
    language: "Portuguese",
    ssn: "744-91-0302",
    money: "$734.39",
  },
  {
    fullName: "Adriano Temby",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Tetum",
    ssn: "288-18-3486",
    money: "$299.81",
  },
  {
    fullName: "Mikol Jirak",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Catalan",
    ssn: "367-17-9869",
    money: "$103.64",
  },
  {
    fullName: "Ynes Mawford",
    gender: "Female",
    jobTitle: "Assistant Media Planner",
    language: "Tetum",
    ssn: "304-55-0893",
    money: "$830.72",
  },
  {
    fullName: "Veronique Merrisson",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Persian",
    ssn: "606-20-3171",
    money: "$961.48",
  },
  {
    fullName: "Davey Wolton",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Papiamento",
    ssn: "809-13-2726",
    money: "$982.04",
  },
  {
    fullName: "Harris Geleman",
    gender: "Male",
    jobTitle: "Media Manager I",
    language: "Azeri",
    ssn: "165-67-9456",
    money: "$22.78",
  },
];

// 1. 성별이 남성이고 직업(jobTitle)이 Engineer가 포함된 사람들만 나타내기!
const q1 = data.filter(
  (x) => x.gender == "Male" && x.jobTitle.includes("Engineer")
);
console.log(q1);

// 2. 이름에서 가족이름을 없애고, ssn을 하이픈 없애고, money를 달러에서 원화로 환율 적용시킨후 나타내기!

// const q2 = data.map((x) => {
//   const firstName = x.fullName.split(" ")[0];
//   const ssn = x.ssn.replace(/-/g, "");

//   const moneyInDollar = parseFloat(x.money.replace("$", ""));
//   const moneyInKRW = moneyInDollar * 1300;

//   return {
//     ...x,
//     fullName: firstName,
//     ssn: ssn,
//     money: `${moneyInKRW}원`,
//   };
// });

// console.log(q2);

const q2 = data.map((x) => {
  x.fullName = x.fullName.split(" ")[0];
  x.ssn = x.ssn.split("-").reduce((a, c) => a + c);
  x.money = `${Number(x.money.slice(1, x.money.length)) * 1470} 원`;
  return x;
});
console.log(q2);
